variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

stages:
  - build

services:
  - docker:dind

build:
  image:
    name: jdrouet/docker-with-buildx:stable
  stage: build
  tags:
    - docker
  script:
    - docker info
    - echo $'\nusername='$USERNAME >> .env
    - echo $'\npassword='$PASSWORD >> .env
    - echo $'\nfrom='$FROM >> .env
    - echo $'\nfromName='$FROMNAME >> .env
    - echo $'\nhost='$HOST >> .env
    - echo $'\nuseHtml='$USEHTML >> .env
    - echo $'\nport='$PORT >> .env
    - echo "Logging in to Docker registry..."
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - echo "Building Docker Image..."
    - docker buildx create --name armbuilder --use
    - docker buildx build --platform linux/arm64 --tag $CI_REGISTRY_IMAGE:latest-arm64 --push -f Dockerfile.arm64 .
    - docker build --tag $CI_REGISTRY_IMAGE:latest .
    - echo "Pushing Image to Registry!"
    - docker push $CI_REGISTRY_IMAGE:latest

