version: "3"

services:
  karl-bock-auth-service:
    image: gitlab.ho-me.zone:5003/karl-bock-uni/auth-service:latest
    container_name: kb-auth-service
    restart: always
    hostname: auth-service
    depends_on:
      - karl-bock-auth-service-db
    security_opt:
      - no-new-privileges:true
    networks:
      - mainprod
      - friendzone
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kb-auth.service=kb-auth"
      - "traefik.docker.network=mainprod"
      - "traefik.tcp.routers.kb-auth.tls=true"
      - "traefik.http.routers.kb-auth.entrypoints=websecure"
      - "traefik.http.services.kb-auth.loadbalancer.server.port=8080"
      - "traefik.tcp.routers.kb-auth.rule=HostSNI(`auth.karl-bock.academy`)"
      - "traefik.http.routers.kb-auth.rule=Host(`auth.karl-bock.academy`)"
      - "com.centurylinklabs.watchtower.enable=true"

  karl-bock-auth-service-db:
    image: mysql:8.0
    container_name: kb-auth-db
    restart: always
    hostname: auth-service-db
    environment:
      MYSQL_ROOT_PASSWORD: einstein
      MYSQL_DATABASE: auth
      MYSQL_USER: kb-auth
      MYSQL_PASSWORD: kb-auth
    security_opt:
      - no-new-privileges:true
    networks:
      - friendzone
networks:
  mainprod:
    external: true
  friendzone:
    external: false
